name: Deploy Angular to Azure Web App

on:
  push:
    branches:
      - master   # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # or 18, matching your Angular setup

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production
        # or just: ng build --configuration=production
        # make sure package.json has "build": "ng build" etc.

      # Adjust this path to your dist folder name
      - name: Archive production build
        run: |
          cd dist
          ls
          cd courts-resume-app\browser
          zip -r ../../../app.zip .
        shell: bash

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: courts-app-service
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
